services:
  sqlite:
    image: nouchka/sqlite3:latest
    container_name: sqlite
    stdin_open: true
    tty: true
    volumes:
      - ./data:/root/db
    entrypoint: [ "sh", "-c", "sqlite3 /root/db/cotacao.db '.databases'" ]
